### PR TITLE
Adding docker-compose.yml and updated documentation

### PR DESCRIPTION
**Pull request by Kage1**
Added docker-compose.yml as proposed by the owner and updated the readme to reflect the new file with usage instructions.

### CODE REVIEW

**Comment by TheNetworkGuy** [comment]
Could you edit the location of the config file to .config.py instead of the /opt/netbox-zabbix? Not everyone will have the script running in that directory so it makes more sense to include the file from the directory in which both files are found. Since this is also the case in the Git repo :)

**Comment by Kage1** [comment]
> Could you edit the location of the config file to .config.py instead of the /opt/netbox-zabbix? Not everyone will have the script running in that directory so it makes more sense to include the file from the directory in which both files are found. Since this is also the case in the Git repo :)

The portion of the docker-compose volume map after the colon : is the internal map to the docker container which is mapped to /opt/netbox-zabbix. This is where the file lives in the docker container.

The host file system could be updated to reference the same directory where the compose file is run at.

**Comment by Kage1** [comment]
I'm not very good with dealing with PR's... Do I need to close this one and create a new PR or is there a way to update this one to include the updated compose file?

**Comment by TheNetworkGuy** [comment]
I'll close this PR for now due to work on several other branches and a plan to completely renew the documentation as stated in #66. Thanks nontheless for your PR but right now i need more help for testing other milestones such as #30 :)

**Pull request closed without merging**
