### PR TITLE
Code cleanup and automated GitHub pylint workflow

### PR DESCRIPTION
**Pull request by q1x**
I've added a workflow for automated GitHub pylint checks and worked out most of the pylint issues by doing some code cleanup.
Other issues have been accepted and ignored for now :)

Would be great to merge and keep an eye on code consistency from now on, this will help when we start moving to automated container images.

### CODE REVIEW

**Comment by q1x** [comment]
Added Dockerfile and needed workflows to build GHCR images.

**Comment by TheNetworkGuy** [comment]
Could you elaborate a bit more in regards to https://github.com/TheNetworkGuy/netbox-zabbix-sync/pull/55/commits/0d7c581ee2d0bf3f0b2731110cd7107d249c8956? From what i can tell the pynetbox module should generate the exception (should something go wrong with creating a new journal entry) and not a new exception class.

**Comment by q1x** [comment]
> Could you elaborate a bit more in regards to [0d7c581](https://github.com/TheNetworkGuy/netbox-zabbix-sync/commit/0d7c581ee2d0bf3f0b2731110cd7107d249c8956)? From what i can tell the pynetbox module should generate the exception (should something go wrong with creating a new journal entry) and not a new exception class.

During testing I actually hit that exception and it failed for me (not sure what the error was exactly), creating a class for it seems to have fixed it.

**Comment by q1x** [comment]
> Another note: something happend in the formatting of [71f604a](https://github.com/TheNetworkGuy/netbox-zabbix-sync/commit/71f604a6f6945bd10d556b61dda21eea99c0393d) which makes it very hard for me to see the difference in between commits. Is there any way how you can correct this? :)

I've reverted the file, please see 5b08d27a5e78cc1a80f301e30f4ed495021b04c6 as that shows the changes needed for Host Inventory as well as nested groupings.

**Comment by q1x** [comment]
> And it is _not_ throwing proxy errors for me. I have `full_proxy_sync = True` in config.py.
Found it and fixed in 091c9746c023e5ff55b83b1ed61c42eb738214d4

**Comment by q1x** [comment]
With regard to the `raise SyncInventoryError(e) from e` lines, those where recommended by pylint and I've just inserted those where it was complaining.

I will need to check what the idea behind it really is :)

**Comment by q1x** [comment]
> With regard to the `raise SyncInventoryError(e) from e` lines, those where recommended by pylint and I've just inserted those where it was complaining.
> 
> I will need to check what the idea behind it really is :)

So, pylint was throwing these warning:

`netbox_zabbix_sync.py:547:16: W0707: Consider explicitly re-raising using 'raise SyncExternalError(e) from e' (raise-missing-from)'

See [docs](https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/raise-missing-from.html) for more info.

I do seem to have added this statement on a few places where it wasn't needed, I've removed those in 634f4b77d5d7d6f60a427851546f92ec50e1386f. Pylint is still happy  🎉

**Comment by q1x** [comment]
Thanks a bunch!

**Pull request merged**
